### ISSUE TITLE
Fix life-cycle of bugs

### ISSUE THREAD

**Issue by nt1m** [nchevobbe/bugzilla-timeline#22]
A bug's life-cycle should start from the last time the assignee got assigned, and should end when the bug becomes RESOLVED FIXED.

The current timeline shows the beginning of the bug as when it got filed, but the timeline allows you to track your bugs' progress, so we don't care about what happened before you got assigned, and we also don't care about what happens after the bug is RESOLVED.

**Comment by nchevobbe** [comment]
Resolved in https://github.com/nchevobbe/bugzilla-timeline/pull/29
