### ISSUE TITLE
Some marker for RESOLVED other than fixed would be nice

### ISSUE THREAD

**Issue by hwine** [nchevobbe/bugzilla-timeline#23]
Thanks to your tool, I was motivated to clean up some long open bugs \o/

I noticed that only bugs marked "RESOLVED FIXED" get a terminating dot on the main page. Many of my bugs close for other reasons.  It would be nice to have an indication on the main page that the bug has been dealt with (closed), even if it wasn't R/F.

As it displays now, until a week or so passes, I can not tell the difference between bugs on which I've not taken any action vs bugs which are closed not fixed. E.g. my current display is:
![screen shot 2016-08-23 at 09 26 11](https://cloud.githubusercontent.com/assets/132412/17900361/dd7b95e8-6913-11e6-9c3a-f18807f2256e.png)

I'm no UX designer, but any of the following would meet my needs:
- bug number in ~~strikeout~~ text in hover balloon
- different terminator on line - maybe a vertical bar?

**Comment by nchevobbe** [comment]
Hi Hal, 
I was indeed thinking about a vertical bar as a terminator, let's try that

**Comment by hwine** [comment]
awesome - let me know how I can help -- test or document that is.

**Comment by hwine** [comment]
Love it! 💯 Thanks!
